scalar DateTime

type Livre {
    id: Int!
    titre: String!
    resume: String!
    dateParution: DateTime
    dateParutionFrance: DateTime
    auteur: Auteur!     # ← Objet complet, pas juste l'ID
    themes: [Theme!]    # ← Objets complets
    pays: Pays!         # ← Objet complet
    nbPage: Int
    createdAt: DateTime!
}

