scalar DateTime

type Livre {
    id: Int!
    titre: String!
    resume: String!
    dateParution: DateTime          
    dateParutionFrance: DateTime    
    auteur: Auteur!
    themes: [Theme!]!
    pays: Pays!
    nbPage: Int                     
    createdAt: DateTime!            
}

input CreateLivreInput {
    titre: String!
    resume: String!
    dateParution: DateTime
    dateParutionFrance: DateTime
    auteurId: Int!
    paysId: Int!
    nbPage: Int
}

input UpdateLivreInput {
    titre: String!
    resume: String!
    dateParution: DateTime
    dateParutionFrance: DateTime
    auteurId: Int!
    paysId: Int!
    nbPage: Int
}